// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyqQ9ygAlJu4qhuCnI7dMcHXY-Hglms3c',
    appId: '1:882737043147:android:7d04606d2b2fad605ced4e',
    messagingSenderId: '882737043147',
    projectId: 'vamvam-54cac',
    storageBucket: 'vamvam-54cac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGiF3vcTFfDvDLKfNmBkR1WucvEfKuquU',
    appId: '1:882737043147:ios:c6ad06ff0a257d0e5ced4e',
    messagingSenderId: '882737043147',
    projectId: 'vamvam-54cac',
    storageBucket: 'vamvam-54cac.appspot.com',
    iosBundleId: 'com.vam.vam',
  );

}
